In [1]:
import sys
import pandas as pd
import numpy as np
# 读入train.csv，繁体字以big5编码
data = pd.read_csv('hw1/train.csv', encoding = 'big5')
# 显示前10行
data.head(10)

日期  測站        測項     0     1     2     3     4     5     6  ...  \
0  2014/1/1  豐原  AMB_TEMP    14    14    14    13    12    12    12  ...   
1  2014/1/1  豐原       CH4   1.8   1.8   1.8   1.8   1.8   1.8   1.8  ...   
2  2014/1/1  豐原        CO  0.51  0.41  0.39  0.37  0.35   0.3  0.37  ...   
3  2014/1/1  豐原      NMHC   0.2  0.15  0.13  0.12  0.11  0.06   0.1  ...   
4  2014/1/1  豐原        NO   0.9   0.6   0.5   1.7   1.8   1.5   1.9  ...   
5  2014/1/1  豐原       NO2    16   9.2   8.2   6.9   6.8   3.8   6.9  ...   
6  2014/1/1  豐原       NOx    17   9.8   8.7   8.6   8.5   5.3   8.8  ...   
7  2014/1/1  豐原        O3    16    30    27    23    24    28    24  ...   
8  2014/1/1  豐原      PM10    56    50    48    35    25    12     4  ...   
9  2014/1/1  豐原     PM2.5    26    39    36    35    31    28    25  ...   

     14    15    16    17    18    19    20    21    22    23  
0    22    22    21    19    17    16    15    15    15    15  
1   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8  
2  0.37  0.37  0.47  0.69  0.56  0.45  0.38  0.35  0.36  0.32  
3   0.1  0.13  0.14  0.23  0.18  0.12   0.1  0.09   0.1  0.08  
4   2.5   2.2   2.5   2.3   2.1   1.9   1.5   1.6   1.8   1.5  
5    11    11    22    28    19    12   8.1     7   6.9     6  
6    14    13    25    30    21    13   9.7   8.6   8.7   7.5  
7    65    64    51    34    33    34    37    38    38    36  
8    52    51    66    85    85    63    46    36    42    42  
9    36    45    42    49    45    44    41    30    24    13  

[10 rows x 27 columns]

In [2]:
data.shape

(4320, 27)

In [3]:
# 丢弃前两列，需要的是从第三列开始的数值
data = data.iloc[:, 3:]
# 把降雨的NR字符变成数值0
data[data == 'NR'] = 0
# 把dataframe转换成numpy的数组
raw_data = data.to_numpy()
raw_data

array([['14', '14', '14', ..., '15', '15', '15'],
       ['1.8', '1.8', '1.8', ..., '1.8', '1.8', '1.8'],
       ['0.51', '0.41', '0.39', ..., '0.35', '0.36', '0.32'],
       ...,
       ['36', '55', '72', ..., '118', '100', '105'],
       ['1.9', '2.4', '1.9', ..., '1.5', '2', '2'],
       ['0.7', '0.8', '1.8', ..., '1.6', '1.8', '2']], dtype=object)

In [4]:
raw_data.shape

(4320, 24)

In [5]:
month_data = {}
for month in range(12):
    sample = np.empty([18, 480])
    for day in range(20):
        sample[:, day * 24 : (day + 1) * 24] = raw_data[18 * (20 * month + day) : 18 * (20 * month + day + 1), :]
    month_data[month] = sample

In [13]:
x = np.empty([12 * 471, 18 * 9], dtype = float)
y = np.empty([12 * 471, 1], dtype = float)
for month in range(12):
    for day in range(20):
        for hour in range(24):
            if day == 19 and hour > 14:
                continue
            x[month * 471 + day * 24 + hour, :] = month_data[month][:,day * 24 + hour : day * 24 + hour + 9].reshape(1, -1) #vector dim:18*9 (9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9)
            y[month * 471 + day * 24 + hour, 0] = month_data[month][9, day * 24 + hour + 9] #value
print(x)
print(y)
print(len(x))
print(len(y))

[[14.  14.  14.  ...  2.   2.   0.5]
 [14.  14.  13.  ...  2.   0.5  0.3]
 [14.  13.  12.  ...  0.5  0.3  0.8]
 ...
 [17.  18.  19.  ...  1.1  1.4  1.3]
 [18.  19.  18.  ...  1.4  1.3  1.6]
 [19.  18.  17.  ...  1.3  1.6  1.8]]
[[30.]
 [41.]
 [44.]
 ...
 [17.]
 [24.]
 [29.]]
5652
5652


In [7]:
mean_x = np.mean(x, axis = 0) #18 * 9 
std_x = np.std(x, axis = 0) #18 * 9 
for i in range(len(x)): #12 * 471
    for j in range(len(x[0])): #18 * 9 
        if std_x[j] != 0:
            x[i][j] = (x[i][j] - mean_x[j]) / std_x[j]
x

array([[-1.35825331, -1.35883937, -1.359222  , ...,  0.26650729,
         0.2656797 , -1.14082131],
       [-1.35825331, -1.35883937, -1.51819928, ...,  0.26650729,
        -1.13963133, -1.32832904],
       [-1.35825331, -1.51789368, -1.67717656, ..., -1.13923451,
        -1.32700613, -0.85955971],
       ...,
       [-0.88092053, -0.72262212, -0.56433559, ..., -0.57693779,
        -0.29644471, -0.39079039],
       [-0.7218096 , -0.56356781, -0.72331287, ..., -0.29578943,
        -0.39013211, -0.1095288 ],
       [-0.56269867, -0.72262212, -0.88229015, ..., -0.38950555,
        -0.10906991,  0.07797893]])

In [8]:
import math
x_train_set = x[: math.floor(len(x) * 0.8), :]
y_train_set = y[: math.floor(len(y) * 0.8), :]
x_validation = x[math.floor(len(x) * 0.8): , :]
y_validation = y[math.floor(len(y) * 0.8): , :]
print(x_train_set)
print(y_train_set)
print(x_validation)
print(y_validation)
print(len(x_train_set))
print(len(y_train_set))
print(len(x_validation))
print(len(y_validation))

[[-1.35825331 -1.35883937 -1.359222   ...  0.26650729  0.2656797
  -1.14082131]
 [-1.35825331 -1.35883937 -1.51819928 ...  0.26650729 -1.13963133
  -1.32832904]
 [-1.35825331 -1.51789368 -1.67717656 ... -1.13923451 -1.32700613
  -0.85955971]
 ...
 [ 0.86929969  0.70886668  0.38952809 ...  1.39110073  0.2656797
  -0.39079039]
 [ 0.71018876  0.39075806  0.07157353 ...  0.26650729 -0.39013211
  -0.39079039]
 [ 0.3919669   0.07264944  0.07157353 ... -0.38950555 -0.39013211
  -0.85955971]]
[[30.]
 [41.]
 [44.]
 ...
 [ 7.]
 [ 5.]
 [14.]]
[[ 0.07374504  0.07264944  0.07157353 ... -0.38950555 -0.85856912
  -0.57829812]
 [ 0.07374504  0.07264944  0.23055081 ... -0.85808615 -0.57750692
   0.54674825]
 [ 0.07374504  0.23170375  0.23055081 ... -0.57693779  0.54674191
  -0.1095288 ]
 ...
 [-0.88092053 -0.72262212 -0.56433559 ... -0.57693779 -0.29644471
  -0.39079039]
 [-0.7218096  -0.56356781 -0.72331287 ... -0.29578943 -0.39013211
  -0.1095288 ]
 [-0.56269867 -0.72262212 -0.88229015 ... -0.3895055

In [9]:
dim = 18 * 9 + 1
w = np.zeros([dim, 1])
x = np.concatenate((np.ones([12 * 471, 1]), x), axis = 1).astype(float)
learning_rate = 3
iter_time = 1000
adagrad = np.zeros([dim, 1])
eps = 0.0000000001
for t in range(iter_time):
    loss = np.sqrt(np.sum(np.power(np.dot(x, w) - y, 2))/471/12)#rmse
    if(t%100==0):
        print(str(t) + ":" + str(loss))
    gradient = 2 * np.dot(x.transpose(), np.dot(x, w) - y) #dim*1
    adagrad += gradient ** 2
    w = w - learning_rate * gradient / np.sqrt(adagrad + eps)
np.save('weight.npy', w)

0:27.071214829194115
100:7.0426766797771805
200:6.509563474857687
300:6.268547066717954
400:6.130698670738399
500:6.040870084026885
600:5.977313995435614
700:5.929812669593297
800:5.892910109473008
900:5.863407898183062


In [10]:
# 读入测试数据test.csv
testdata = pd.read_csv('hw1/test.csv', header = None, encoding = 'big5')
# 丢弃前两列，需要的是从第3列开始的数据
test_data = testdata.iloc[:, 2:]
# 把降雨为NR字符变成数字0
test_data[test_data == 'NR'] = 0
# 将dataframe变成numpy数组
test_data = test_data.to_numpy()
# 将test数据也变成 240 个维度为 18 * 9 + 1 的数据。
test_x = np.empty([240, 18*9], dtype = float)
for i in range(240):
    test_x[i, :] = test_data[18 * i: 18* (i + 1), :].reshape(1, -1)
for i in range(len(test_x)):
    for j in range(len(test_x[0])):
        if std_x[j] != 0:
            test_x[i][j] = (test_x[i][j] - mean_x[j]) / std_x[j]
test_x = np.concatenate((np.ones([240, 1]), test_x), axis = 1).astype(float)
test_x

E:\Anaconda\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
E:\Anaconda\lib\site-packages\pandas\core\frame.py:3093: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._where(-key, value, inplace=True)


array([[ 1.        , -0.24447681, -0.24545919, ..., -0.67065391,
        -1.04594393,  0.07797893],
       [ 1.        , -1.35825331, -1.51789368, ...,  0.17279117,
        -0.10906991, -0.48454426],
       [ 1.        ,  1.5057434 ,  1.34508393, ..., -1.32666675,
        -1.04594393, -0.57829812],
       ...,
       [ 1.        ,  0.3919669 ,  0.54981237, ...,  0.26650729,
        -0.20275731,  1.20302531],
       [ 1.        , -1.8355861 , -1.8360023 , ..., -1.04551839,
        -1.13963133, -1.14082131],
       [ 1.        , -1.35825331, -1.35883937, ...,  2.98427476,
         3.26367657,  1.76554849]])

In [11]:
w = np.load('weight.npy')
ans_y = np.dot(test_x, w)
ans_y

array([[ 4.70027544e+00],
       [ 1.70218150e+01],
       [ 2.45419934e+01],
       [ 8.29172854e+00],
       [ 2.79542189e+01],
       [ 2.17619233e+01],
       [ 2.28971425e+01],
       [ 3.11639076e+01],
       [ 1.73717658e+01],
       [ 5.84502120e+01],
       [ 1.48973529e+01],
       [ 1.06398506e+01],
       [ 6.11718078e+01],
       [ 5.24685067e+01],
       [ 2.18991241e+01],
       [ 1.13614845e+01],
       [ 3.17012952e+01],
       [ 6.82628267e+01],
       [-1.17293487e+00],
       [ 1.66280136e+01],
       [ 4.22854041e+01],
       [ 7.14270764e+01],
       [ 9.24531551e+00],
       [ 1.80213462e+01],
       [ 1.50031202e+01],
       [ 3.82594739e+01],
       [ 1.38859913e+01],
       [ 7.27374003e+01],
       [ 7.57193204e+00],
       [ 5.52094192e+01],
       [ 2.31221771e+01],
       [ 8.22495385e+00],
       [ 2.47510900e+00],
       [ 2.14293345e+01],
       [ 3.01951621e+01],
       [ 3.67183595e+01],
       [ 4.26651233e+01],
       [ 2.97726227e+01],
       [ 4.4

In [12]:
import csv
with open('submit1.csv', mode='w', newline='') as submit_file:
    csv_writer = csv.writer(submit_file)
    header = ['id', 'value']
    print(header)
    csv_writer.writerow(header)
    for i in range(240):
        row = ['id_' + str(i), ans_y[i][0]]
        csv_writer.writerow(row)
        print(row)

['id', 'value']
['id_0', 4.700275439105574]
['id_1', 17.021815034532978]
['id_2', 24.541993377299782]
['id_3', 8.291728538052535]
['id_4', 27.954218890575078]
['id_5', 21.76192327991737]
['id_6', 22.897142462338355]
['id_7', 31.16390756690322]
['id_8', 17.37176583695675]
['id_9', 58.45021199766112]
['id_10', 14.897352949506612]
['id_11', 10.639850598328623]
['id_12', 61.171807782765676]
['id_13', 52.46850666744123]
['id_14', 21.899124082121816]
['id_15', 11.361484544319394]
['id_16', 31.70129515265802]
['id_17', 68.26282666901734]
['id_18', -1.1729348687218946]
['id_19', 16.628013602099912]
['id_20', 42.28540412539497]
['id_21', 71.42707643137472]
['id_22', 9.245315506863713]
['id_23', 18.021346199896897]
['id_24', 15.003120213652773]
['id_25', 38.25947393643945]
['id_26', 13.88599131963223]
['id_27', 72.73740026986518]
['id_28', 7.571932042477683]
['id_29', 55.209419205508375]
['id_30', 23.12217713692685]
['id_31', 8.224953846471934]
['id_32', 2.4751090020383675]
['id_33', 21.42933453